# Generated by Django 5.1.15 on 2026-07-02 16:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_text_hash", models.CharField(max_length=64, unique=True)),
                (
                    "source_lang",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English"), ("es", "Español")],
                        max_length=2,
                    ),
                ),
                (
                    "target_lang",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English"), ("es", "Español")],
                        max_length=2,
                    ),
                ),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "translation_cache",
                "indexes": [models.Index(fields=["expires_at"], name="idx_transcache_expires")],
            },
        ),
    ]
