# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationUnmatched',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(max_length=255)),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('reason', models.CharField(choices=[('no_sku', 'No SKU column / value'), ('no_match', 'Could not match an existing product'), ('duplicate_match', 'Multiple candidate matches'), ('invalid_format', 'Invalid format'), ('missing_required_field', 'Missing required field')], max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.EmailField(blank=True, default='', max_length=254)),
                ('resolution_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'migration_unmatched',
                'ordering': ['source_file', 'source_row_number'],
                'indexes': [models.Index(fields=['source_file', 'resolved_at'], name='idx_migration_unmatched_src'), models.Index(fields=['reason'], name='idx_migration_unmatched_rsn')],
            },
        ),
    ]
