# Generated by Django 5.1.15 on 2026-07-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_migration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationunmatched",
            name="resolution_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ignore", "Ne rien faire (ignorer)"),
                    ("create", "Produit créé"),
                    ("delete", "Supprimer (doublon / rebut)"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
