# Generated by Django 5.1.15 on 2026-05-12 13:21

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('simulation_type', models.CharField(choices=[('tariff', 'Tariff (multi-clients)'), ('project', 'Project (single client)')], max_length=16)),
                ('client_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('market_params', models.JSONField(blank=True, default=dict)),
                ('calculation_chain', models.JSONField(blank=True, default=dict)),
                ('stock_purchase_mix_pct', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('symea_margin_rate', models.DecimalField(decimal_places=4, default='0.0600', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator('0.9999')])),
                ('syskern_margin_rate', models.DecimalField(decimal_places=4, default='0.2000', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator('0.9999')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('is_dirty', models.BooleanField(default=True, help_text='True when parameters have been modified since last recalc.')),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['simulation_type'], name='idx_simulations_type'), models.Index(fields=['status'], name='idx_simulations_status'), models.Index(fields=['-created_at'], name='idx_simulations_created')],
            },
        ),
        migrations.CreateModel(
            name='SimulationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_snapshot', models.JSONField(default=dict)),
                ('supplier_snapshot', models.JSONField(default=dict)),
                ('margin_override', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator('0.9999')])),
                ('stock_purchase_mix_pct_override', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('po_net_origin_currency', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_net_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pa_net_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pamp_predictive_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pr_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pv_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('calculation_breakdown', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', help_text="'pending' | 'ok' | 'warning' | 'error' | 'dirty'", max_length=16)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_lines', to='products.product')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='simulations.simulation')),
            ],
            options={
                'db_table': 'simulation_lines',
                'indexes': [models.Index(fields=['simulation'], name='idx_sim_lines_sim'), models.Index(fields=['product'], name='idx_sim_lines_product')],
                'constraints': [models.UniqueConstraint(fields=('simulation', 'product'), name='unique_product_per_simulation')],
            },
        ),
        migrations.CreateModel(
            name='SimulationRecalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_at', models.DateTimeField()),
                ('market_params', models.JSONField()),
                ('odoo_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_chain', models.JSONField()),
                ('stock_purchase_mix_pct', models.IntegerField()),
                ('syskern_margin_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('symea_margin_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('aggregates', models.JSONField()),
                ('trigger_type', models.CharField(choices=[('manual_current_params', 'Manual — current params'), ('manual_refresh_odoo', 'Manual — refresh Odoo'), ('manual_full_refresh', 'Manual — full refresh'), ('line_recalculate', 'Single-line recalc'), ('initial', 'Initial calculation')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalculations', to='simulations.simulation')),
            ],
            options={
                'db_table': 'simulation_recalculations',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['simulation', '-calculated_at'], name='idx_recalc_simulation_date')],
            },
        ),
    ]
