# Generated by Django 5.1.15 on 2026-05-12 13:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='symea_margin_rate',
            field=models.DecimalField(decimal_places=4, default='0.0600', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.9999'))]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='syskern_margin_rate',
            field=models.DecimalField(decimal_places=4, default='0.2000', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.9999'))]),
        ),
        migrations.AlterField(
            model_name='simulationline',
            name='margin_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.9999'))]),
        ),
    ]
