# Generated by Django 5.1.15 on 2026-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_simulation_sale_incoterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrecalculation',
            name='line_snapshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='simulationrecalculation',
            name='trigger_type',
            field=models.CharField(choices=[('manual_current_params', 'Manual — current params'), ('manual_refresh_odoo', 'Manual — refresh Odoo'), ('manual_full_refresh', 'Manual — full refresh'), ('line_recalculate', 'Single-line recalc'), ('initial', 'Initial calculation'), ('finalize', 'Finalize snapshot')], max_length=32),
        ),
    ]
