# Generated by Django 5.1.15 on 2026-06-22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0005_simulationrecalculation_line_snapshots_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "simulation_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "recalculation_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list, size=None
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "saved_comparisons",
                "ordering": ["-created_at"],
            },
        ),
    ]
