# Generated by Django 5.1.15 on 2026-06-23 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_savedcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcomparison',
            name='recalculation_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='savedcomparison',
            name='simulation_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
    ]
