# Generated by Django 5.1.15 on 2026-07-14 09:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0007_alter_savedcomparison_recalculation_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationline",
            name="force_manual_mix",
            field=models.BooleanField(
                default=False,
                help_text="Disable the quantity-driven auto-mix; use the manual mix instead.",
            ),
        ),
        migrations.AddField(
            model_name="simulationline",
            name="pa_coefficient_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Direct multiplier on the PA net (alternative to detailed transport).",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
            ),
        ),
        migrations.AddField(
            model_name="simulationline",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Project quantity per SKU; drives the auto stock/purchase mix.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
