# Generated by Django 5.1.15 on 2026-07-21 15:29

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulations", "0009_invalidate_stale_sale_margin_breakdowns"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationline",
            name="previous_pv_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="PV just before the latest successful recalculation (FEEDBACK 2).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simulationline",
            name="pa_coefficient_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Per-line PA transport coefficient; NULL inherits the simulation chain.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
            ),
        ),
    ]
