# Generated by Django 5.1.15 on 2026-07-13 14:30

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code fournisseur ne peut contenir que lettres, chiffres, tirets et underscores.",
                                regex="^[A-Za-z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("factory_code_default", models.CharField(blank=True, default="", max_length=16)),
                (
                    "currency_default",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="RMB",
                        max_length=3,
                    ),
                ),
                (
                    "incoterm_default",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "Ex Works"),
                            ("FCA", "Free Carrier"),
                            ("FAS", "Free Alongside Ship"),
                            ("FOB", "Free On Board"),
                            ("CFR", "Cost and Freight"),
                            ("CIF", "Cost, Insurance and Freight"),
                            ("CPT", "Carriage Paid To"),
                            ("CIP", "Carriage and Insurance Paid To"),
                            ("DAP", "Delivered At Place"),
                            ("DPU", "Delivered at Place Unloaded"),
                            ("DDP", "Delivered Duty Paid"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "suppliers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_suppliers_name"),
                    models.Index(fields=["code"], name="idx_suppliers_code"),
                    models.Index(fields=["is_active"], name="idx_suppliers_active"),
                ],
            },
        ),
    ]
