# Generated by Django 5.1.15 on 2026-07-20 09:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierImportMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("column_map", models.JSONField(default=dict)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_mappings",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_import_mappings",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["supplier"], name="idx_import_map_supplier")],
            },
        ),
    ]
