# Generated by Django 5.1.15 on 2026-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_supplierimportmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierimportmapping",
            name="header_row",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
