# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransportMode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.JSONField(help_text="Multilingual label")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maritime", "Maritime"),
                            ("road", "Road"),
                            ("air", "Air"),
                            ("rail", "Rail"),
                        ],
                        max_length=16,
                    ),
                ),
                ("default_pallet_capacity", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "transport_modes",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="MarketParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter_type",
                    models.CharField(
                        choices=[("copper_price", "Copper spot price"), ("fx_rate", "FX rate")],
                        max_length=16,
                    ),
                ),
                (
                    "copper_market",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LME", "London Metal Exchange"),
                            ("SHE", "Shanghai Futures Exchange"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                (
                    "copper_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "copper_currency",
                    models.CharField(
                        blank=True,
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="",
                        max_length=3,
                    ),
                ),
                ("copper_unit", models.CharField(blank=True, default="tonne", max_length=16)),
                (
                    "fx_from_currency",
                    models.CharField(
                        blank=True,
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "fx_to_currency",
                    models.CharField(
                        blank=True,
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "market_parameters",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["parameter_type", "-valid_from"], name="idx_market_params_type"
                    )
                ],
            },
        ),
    ]
