# Generated by Django 5.1.15 on 2026-07-15 14:31

import uuid
from django.db import migrations, models

from apps.market.seeds import TRANSPORT_PRESETS, seed_transport_presets


def forwards(apps, schema_editor):
    transport_preset_model = apps.get_model("market", "TransportPreset")
    seed_transport_presets(transport_preset_model)


def backwards(apps, schema_editor):
    transport_preset_model = apps.get_model("market", "TransportPreset")
    transport_preset_model.objects.filter(
        name__in=[e["name"] for e in TRANSPORT_PRESETS],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketparameter_source_and_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('chain_role', models.CharField(choices=[('purchase', 'Purchase (PA)'), ('sale', 'Sale (PV)')], max_length=16)),
                ('transport_mode_code', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('maritime', 'Maritime'), ('road', 'Road'), ('air', 'Air'), ('rail', 'Rail')], max_length=16)),
                ('global_cost', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('RMB', 'Renminbi')], max_length=3)),
                ('pallet_count', models.CharField(blank=True, default='', max_length=16)),
                ('from_location', models.CharField(blank=True, default='', max_length=128)),
                ('to_location', models.CharField(blank=True, default='', max_length=128)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded defaults — cannot be deleted via API.')),
            ],
            options={
                'db_table': 'transport_presets',
                'ordering': ['chain_role', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('chain_role', 'name'), name='uniq_transport_preset_name_role')],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
