# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odoo_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_prospect', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('address_street', models.CharField(blank=True, default='', max_length=255)),
                ('address_city', models.CharField(blank=True, default='', max_length=128)),
                ('address_zip', models.CharField(blank=True, default='', max_length=32)),
                ('address_country', models.CharField(blank=True, default='', max_length=64)),
                ('preferred_currency', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('RMB', 'Renminbi')], default='', max_length=3)),
                ('preferred_incoterm', models.CharField(blank=True, choices=[('EXW', 'Ex Works'), ('FCA', 'Free Carrier'), ('FAS', 'Free Alongside Ship'), ('FOB', 'Free On Board'), ('CFR', 'Cost and Freight'), ('CIF', 'Cost, Insurance and Freight'), ('CPT', 'Carriage Paid To'), ('CIP', 'Carriage and Insurance Paid To'), ('DAP', 'Delivered At Place'), ('DPU', 'Delivered at Place Unloaded'), ('DDP', 'Delivered Duty Paid')], default='', max_length=4)),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('segment', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('odoo_last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['odoo_id'], name='idx_clients_odoo'), models.Index(fields=['name'], name='idx_clients_name'), models.Index(fields=['is_prospect'], name='idx_clients_prospect')],
            },
        ),
    ]
