# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('auto_daily', 'Daily cron'), ('manual', 'Manual trigger'), ('on_demand', 'On-demand (product create/update)')], max_length=16)),
                ('scope', models.CharField(choices=[('all', 'All'), ('products', 'Products'), ('stock', 'Stock'), ('clients', 'Clients'), ('suppliers', 'Suppliers'), ('purchases_sales', 'Pending purchases & sales')], max_length=32)),
                ('odoo_api_version', models.CharField(help_text="'v16' or 'v19' — captured for audit when adapters swap.", max_length=4)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_failure', 'Partial failure'), ('failed', 'Failed')], max_length=20)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='[{"item_id": "...", "error_message": "..."}, ...]')),
                ('triggered_by', models.CharField(blank=True, default='', help_text="'system' or 'manual'", max_length=32)),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type', '-started_at'], name='idx_sync_type_date'), models.Index(fields=['status'], name='idx_sync_status')],
            },
        ),
    ]
