# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.JSONField(help_text="Multilingual label")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cgv", "CGV — Conditions générales de vente"),
                            ("warranty", "Warranty"),
                            ("quality", "Quality management"),
                            ("project_reference", "Project references"),
                            ("company", "Company presentation"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file_url", models.TextField()),
                ("file_size_bytes", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("fr", "Français"), ("en", "English"), ("es", "Español")],
                        default="",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "document_library",
                "ordering": ["category", "display_order"],
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="idx_doc_cat_active")
                ],
            },
        ),
    ]
