# Generated by Django 5.1.15 on 2026-06-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("products", "0004_product_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlibrary",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Set on soft-delete; purged after 30 days.", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentlibrary",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentlibrary",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="documentlibrary",
            name="uploaded_by",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="documentlibrary",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="documentlibrary",
            index=models.Index(fields=["category", "language"], name="idx_doc_cat_lang"),
        ),
        migrations.AddIndex(
            model_name="documentlibrary",
            index=models.Index(fields=["product"], name="idx_doc_product"),
        ),
        migrations.AddIndex(
            model_name="documentlibrary",
            index=models.Index(fields=["deleted_at"], name="idx_doc_deleted_at"),
        ),
    ]
