# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.TextField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Attribute code must be snake_case (lowercase, digits, underscores).",
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        help_text='Multilingual {"fr": "...", "en": "...", "es": "..."}'
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("structural", "Structural"),
                            ("technical", "Technical"),
                            ("marketing", "Marketing"),
                            ("commercial", "Commercial"),
                            ("logistic", "Logistic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("select", "Single choice"),
                            ("multiselect", "Multiple choice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='For select / multiselect: [{"value": "...", "label": {...}}]',
                        null=True,
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("is_required", models.BooleanField(default=False)),
                ("is_searchable", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "attribute_registry",
                "ordering": ["display_order", "code"],
                "indexes": [models.Index(fields=["category"], name="idx_attr_registry_category")],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="attributes.attributeregistry",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_attribute_values",
                "indexes": [
                    models.Index(fields=["product"], name="idx_pav_product"),
                    models.Index(fields=["attribute"], name="idx_pav_attribute"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["value"], name="idx_pav_value_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "attribute"), name="unique_product_attribute"
                    )
                ],
            },
        ),
    ]
