# Generated by Django 5.1.15 on 2026-07-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_attributeregistry_is_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeregistry',
            name='default_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
