# Generated by Django 5.1.15 on 2026-05-12 13:21

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_type', models.CharField(choices=[('tariff', 'Tariff (multi-clients)'), ('project', 'Project (single client)')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('client_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_info', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('RMB', 'Renminbi')], max_length=3)),
                ('incoterm', models.CharField(choices=[('EXW', 'Ex Works'), ('FCA', 'Free Carrier'), ('FAS', 'Free Alongside Ship'), ('FOB', 'Free On Board'), ('CFR', 'Cost and Freight'), ('CIF', 'Cost, Insurance and Freight'), ('CPT', 'Carriage Paid To'), ('CIP', 'Carriage and Insurance Paid To'), ('DAP', 'Delivered At Place'), ('DPU', 'Delivered at Place Unloaded'), ('DDP', 'Delivered Duty Paid')], max_length=4)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=2)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('validity_duration_days', models.IntegerField(blank=True, null=True)),
                ('export_format', models.CharField(choices=[('excel', 'Excel'), ('catalog', 'Gamma catalog (tariff)'), ('devis_gamma', 'Gamma quote (project)')], max_length=16)),
                ('ai_instructions', models.TextField(blank=True, default='')),
                ('price_justification', models.TextField(blank=True, default='')),
                ('attached_document_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('custom_attached_files', models.JSONField(blank=True, default=list, help_text='[{"filename": "...", "storage_path": "..."}]')),
                ('generated_file_url', models.TextField(blank=True, default='')),
                ('gamma_document_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('won', 'Won (project only)'), ('lost', 'Lost (project only)'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True, default='')),
                ('version_number', models.IntegerField(default=1)),
                ('previous_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='offers.offer')),
                ('simulation', models.ForeignKey(help_text='Must be a finalized simulation (CDC §7.9).', on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='simulations.simulation')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Filled for project offers; null for tariffs.', max_digits=12, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_lines', to='products.product')),
                ('simulation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_lines', to='simulations.simulationline')),
            ],
            options={
                'db_table': 'offer_lines',
                'ordering': ['offer_id', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type'], name='idx_offers_type'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status'], name='idx_offers_status'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_to'], name='idx_offers_valid_to'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['previous_offer'], name='idx_offers_previous'),
        ),
        migrations.AddIndex(
            model_name='offerline',
            index=models.Index(fields=['offer'], name='idx_offer_lines_offer'),
        ),
    ]
