# Generated by Django 5.1.15 on 2026-06-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="ai_arguments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="offer",
            name="generation_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="offer",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("error", "Error (retry possible)"),
                ],
                default="pending",
                help_text="Document generation state (separate from the commercial status).",
                max_length=16,
            ),
        ),
    ]
