# Generated by Django 5.1.15 on 2026-07-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_reap_stuck_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="gamma_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("distributeur", "Distributeur"),
                    ("factoring", "Factoring"),
                    ("export", "Export"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
