# Generated by Django 5.1.15 on 2026-05-12 13:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("odoo_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "sku_code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="SKU must contain only uppercase letters, digits and dashes.",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                    ),
                ),
                ("item_code", models.CharField(blank=True, default="", max_length=128)),
                ("parent_reference", models.CharField(blank=True, default="", max_length=64)),
                ("factory_code", models.CharField(blank=True, default="", max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("universe", models.CharField(blank=True, default="", max_length=128)),
                ("family", models.CharField(blank=True, default="", max_length=128)),
                ("range", models.CharField(blank=True, default="", max_length=128)),
                ("sub_range", models.CharField(blank=True, default="", max_length=128)),
                ("brand", models.CharField(blank=True, default="", max_length=128)),
                (
                    "description_marketing",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"fr": "...", "en": "...", "es": "..."}',
                    ),
                ),
                ("description_technical", models.JSONField(blank=True, default=dict)),
                ("hs_code", models.CharField(blank=True, default="", max_length=32)),
                ("gtin", models.CharField(blank=True, default="", max_length=32)),
                ("dop_number", models.CharField(blank=True, default="", max_length=64)),
                ("is_copper_indexed", models.BooleanField(default=False)),
                (
                    "copper_weight_kg_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[("unit", "Unit"), ("km", "Kilometre"), ("m", "Metre")],
                        default="unit",
                        max_length=8,
                    ),
                ),
                ("primary_packaging_qty", models.IntegerField(blank=True, null=True)),
                ("secondary_packaging_qty", models.IntegerField(blank=True, null=True)),
                ("tertiary_packaging_qty", models.IntegerField(blank=True, null=True)),
                ("pallet_qty", models.IntegerField(blank=True, null=True)),
                (
                    "unit_weight_kg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "supply_policy",
                    models.CharField(
                        choices=[
                            ("buy", "Buy & stock"),
                            ("dropship", "Dropship"),
                            ("mixed", "Mixed"),
                        ],
                        default="buy",
                        max_length=16,
                    ),
                ),
                ("is_stockable", models.BooleanField(default=True)),
                (
                    "stock_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "pamp_eur",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("pamp_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("odoo_last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "migration_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("odoo", "Odoo sync"),
                            ("excel_pricing", "Excel — pricing"),
                            ("excel_technical", "Excel — technical"),
                            ("database_internal", "Internal database"),
                            ("manual", "Created manually"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["sku_code"],
                "indexes": [
                    models.Index(fields=["sku_code"], name="idx_products_sku"),
                    models.Index(fields=["odoo_id"], name="idx_products_odoo"),
                    models.Index(
                        fields=["universe", "family", "range", "sub_range"],
                        name="idx_products_hierarchy",
                    ),
                    models.Index(fields=["factory_code"], name="idx_products_factory"),
                    models.Index(fields=["is_active"], name="idx_products_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_name", models.CharField(max_length=255)),
                ("factory_code", models.CharField(blank=True, default="", max_length=16)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "po_base_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "po_currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="RMB",
                        max_length=3,
                    ),
                ),
                ("is_copper_indexed", models.BooleanField(default=False)),
                (
                    "copper_base_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "Ex Works"),
                            ("FCA", "Free Carrier"),
                            ("FAS", "Free Alongside Ship"),
                            ("FOB", "Free On Board"),
                            ("CFR", "Cost and Freight"),
                            ("CIF", "Cost, Insurance and Freight"),
                            ("CPT", "Carriage Paid To"),
                            ("CIP", "Carriage and Insurance Paid To"),
                            ("DAP", "Delivered At Place"),
                            ("DPU", "Delivered at Place Unloaded"),
                            ("DDP", "Delivered Duty Paid"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("incoterm_location", models.CharField(blank=True, default="", max_length=128)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_suppliers",
                "ordering": ["product_id", "-is_active", "supplier_name"],
                "indexes": [models.Index(fields=["product"], name="idx_prod_suppliers_product")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("product",),
                        name="one_active_supplier_per_product",
                    )
                ],
            },
        ),
    ]
