# Generated by Django 5.1.15 on 2026-07-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uom",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
