# Generated by Django 5.1.15 on 2026-07-13 14:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_uom"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_po_base_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "new_po_base_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "po_currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("RMB", "Renminbi")],
                        default="RMB",
                        max_length=3,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Import Excel batch"),
                            ("manual", "Édition manuelle"),
                            ("odoo", "Sync Odoo"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "supplier_price_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="productsupplier",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_links",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddIndex(
            model_name="productsupplier",
            index=models.Index(fields=["supplier"], name="idx_prod_suppliers_supplier"),
        ),
        migrations.AddField(
            model_name="supplierpricehistory",
            name="product_supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="products.productsupplier",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpricehistory",
            index=models.Index(
                fields=["product_supplier", "-created_at"], name="idx_price_hist_link_date"
            ),
        ),
    ]
