# Generated by Django 5.1.15 on 2026-07-22 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_rebackfill_supplier_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplier",
            name="copper_weight_kg_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productsupplier",
            name="is_copper_indexed",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
