"""Tests for POFournisseursLoader (CDC §8.4 — Étape 2).

These tests exercise the normalize_row / build_match_hint / apply_update logic
via a real (tiny) xlsx fixture that mimics the PO sheet structure.

The fixture is generated by generate_po_fixture() below and written to
tests/fixtures/po_sample.xlsx at the start of the test session.

DB: @pytest.mark.django_db(transaction=True) — savepoints require real
transactions, not wrapping in a test transaction.
"""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path

import openpyxl
import pandas as pd
import pytest

from apps.data_migration.loaders.exceptions import InvalidRowError
from apps.data_migration.loaders.loader_po_fournisseurs import POFournisseursLoader
from apps.data_migration.loaders.types import LoaderConfig, NormalizedRow
from apps.data_migration.models import MigrationUnmatched, UnmatchedReason
from apps.products.models import (
    Currency,
    Incoterm,
    MigrationSource,
    Product,
    ProductSupplier,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures"

# ─── Fixture generation ───────────────────────────────────────────────────────

PO_HEADERS = [
    "Unikkern Items code",  # 0
    "Internal Code",  # 1
    "Brand",  # 2
    "Active France Y/N",  # 3
    "Active Export Y/N",  # 4
    "Univers",  # 5
    "Range",  # 6
    "Sub-Range",  # 7
    "Type",  # 8
    "AWG/SIZE",  # 9
    "item code",  # 10
    "Description En",  # 11
    "Description fr",  # 12
    "Tag",  # 13
    "Origin",  # 14
    "Cu (kg/km)",  # 15
    "QTY/Pallet",  # 16
    "Global Trade Item Number (GTIN)",  # 17
    "HS Code",  # 18
    "MOQ ",  # 19
    "Supplier Payment term",  # 20
    "Distributor SC FOB Price (Usd/km)",  # 21
    "MB% FOB Symea",  # 22
    "Supplier",  # 23
]

PO_ROWS = [
    # Row 1: active France, copper-indexed, valid GTIN → match + full enrichment
    (
        "KCFU64PZHDGR5",
        "KCFU64PZHDGR5-21",
        "UKN",
        "Yes",
        "Yes",
        "COPPER",
        "DATA CABLES",
        "SOLID CABLE CAT6",
        "F/UTP",
        "23",
        "U0102001",
        "CAT6 Cable F/UTP grey 500m",
        "CÂBLE CAT6 F/UTP gris 500m",
        "Dca",
        "China",
        "17.5",
        "9",
        "4897108881749",
        "854449 2000",
        "30 km",
        "T/T 60 days",
        "448.92",
        "0.09",
        "HT",
    ),
    # Row 2: same SKU, different factory (Turkey KK) → second ProductSupplier
    (
        "KCFU64PZHDGR5",
        "KCFU64PZHDGR5-E02",
        "UKN",
        "No",
        "Yes",
        "COPPER",
        "DATA CABLES",
        "SOLID CABLE CAT6",
        "F/UTP",
        "23",
        "",
        "CAT6 Cable F/UTP grey 500m TK",
        "",
        "Dca",
        "Turkey",
        "17.5",
        "9",
        "4897108881749",
        "854449 2000",
        "30 km",
        "T/T 30 days",
        "410.00",
        "0.07",
        "KK",
    ),
    # Row 3: no SKU, no identifiers → NO_SKU quarantine
    (
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "#N/A",
        "",
        "",
        "",
        "0",
        "0.09",
        "",
    ),
    # Row 4: SKU present but no match in DB → NO_MATCH quarantine
    (
        "UNKNOWNSKU99",
        "UNKNOWNSKU99-21",
        "UKN",
        "No",
        "No",
        "COPPER",
        "DATA CABLES",
        "SOLID CABLE CAT6",
        "U/UTP",
        "24",
        "",
        "Unknown cable",
        "",
        "Dca",
        "China",
        "15.0",
        "12",
        "#N/A",
        "854449 2000",
        "30 km",
        "T/T 60 days",
        "300.00",
        "0.09",
        "HT",
    ),
    # Row 5: valid SKU, fob_price missing → MISSING_REQUIRED_FIELD quarantine
    (
        "KCUF6A4PZHDBL5",
        "KCUF6A4PZHDBL5-21",
        "UKN",
        "Yes",
        "No",
        "COPPER",
        "DATA CABLES",
        "SOLID CABLE CAT6A",
        "U/FTP",
        "23",
        "",
        "CAT6A cable",
        "",
        "Dca",
        "China",
        "20.0",
        "9",
        "4897108882319",
        "854449 2000",
        "30 km",
        "T/T 60 days",
        "",
        "0.09",
        "HT",
    ),
]


def generate_po_fixture(path: Path) -> None:
    """Write a minimal PO xlsx fixture with 3 metadata rows + header + 5 data rows."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "PO & SC March 2026"

    # Metadata rows (rows 1-2) — copper base in col E (index 4)
    meta = [None] * len(PO_HEADERS)
    ws.append(meta)  # row 1: blank
    meta2 = [None] * len(PO_HEADERS)
    meta2[4] = "3mm copper base"
    meta2[5] = 97000.0
    ws.append(meta2)  # row 2: copper base
    ws.append([None] * len(PO_HEADERS))  # rows 3-12: blank spacers
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))
    ws.append([None] * len(PO_HEADERS))

    ws.append(PO_HEADERS)  # row 13: header
    for row in PO_ROWS:
        ws.append(list(row))  # rows 14-18: data

    # Supplier code list sheet
    ws2 = wb.create_sheet("Supplier code list")
    ws2.append(["", "Supplier's ID", "Supplier code on products"])
    ws2.append(["", "HT", 21])
    ws2.append(["", "KK", "E02"])
    ws2.append(["", "ZD", 17])

    wb.save(path)


PO_FIXTURE = FIXTURE_DIR / "po_sample.xlsx"


@pytest.fixture(scope="module", autouse=True)
def create_po_fixture() -> None:
    FIXTURE_DIR.mkdir(exist_ok=True)
    generate_po_fixture(PO_FIXTURE)


def default_config(**overrides: object) -> LoaderConfig:
    return LoaderConfig(
        file_path=str(PO_FIXTURE),
        sheet_name="PO & SC March 2026",
        header_row=12,
        batch_size=500,
        dry_run=bool(overrides.get("dry_run", False)),
        create_missing=bool(overrides.get("create_missing", False)),
    )


def make_product(sku_code: str, **kwargs: object) -> Product:
    return Product.objects.create(
        sku_code=sku_code,
        name=f"Test {sku_code}",
        migration_source=MigrationSource.MANUAL,
        **kwargs,
    )


# ─── Tests ────────────────────────────────────────────────────────────────────


@pytest.mark.django_db(transaction=True)
class TestPOLoaderReport:
    def setup_method(self) -> None:
        # Create the two products that will match rows 1/2 and 5
        make_product("KCFU64PZHDGR5")
        make_product("KCUF6A4PZHDBL5")
        # Row 4 ("UNKNOWNSKU99") intentionally not in DB → NO_MATCH

    def test_total_rows(self) -> None:
        report = POFournisseursLoader().run(default_config())
        assert report.rows_total == 5

    def test_matched_rows(self) -> None:
        report = POFournisseursLoader().run(default_config())
        # Rows 1 & 2 match KCFU64PZHDGR5; row 5 matches KCUF6A4PZHDBL5 (empty FOB is
        # tolerated → supplier created without a price). Row 3: NO_SKU, Row 4: NO_MATCH.
        assert report.rows_matched == 3

    def test_quarantine_no_sku(self) -> None:
        report = POFournisseursLoader().run(default_config())
        assert report.rows_unmatched.get(UnmatchedReason.NO_SKU, 0) >= 1

    def test_quarantine_no_match(self) -> None:
        report = POFournisseursLoader().run(default_config())
        assert report.rows_unmatched.get(UnmatchedReason.NO_MATCH, 0) == 1

    def test_missing_fob_is_tolerated(self) -> None:
        report = POFournisseursLoader().run(default_config())
        # Empty FOB no longer quarantines — only NO_SKU + NO_MATCH remain.
        assert report.rows_quarantined == 2

    def test_quarantine_records_in_db(self) -> None:
        POFournisseursLoader().run(default_config())
        assert MigrationUnmatched.objects.filter(source_file="po_sample.xlsx").count() == 2


@pytest.mark.django_db(transaction=True)
class TestPOLoaderCreateMissing:
    def setup_method(self) -> None:
        make_product("KCFU64PZHDGR5")
        make_product("KCUF6A4PZHDBL5")
        # Row 4 ("UNKNOWNSKU99") absent → would be NO_MATCH without create_missing.

    def test_creates_unmatched_product(self) -> None:
        report = POFournisseursLoader().run(default_config(create_missing=True))
        assert report.rows_created == 1
        assert Product.objects.filter(sku_code="UNKNOWNSKU99").exists()
        # Only NO_SKU (row 3) remains in quarantine — no SKU to create from.
        assert report.rows_unmatched.get(UnmatchedReason.NO_MATCH, 0) == 0
        assert report.rows_quarantined == 1

    def test_without_flag_still_quarantines(self) -> None:
        report = POFournisseursLoader().run(default_config())
        assert report.rows_created == 0
        assert not Product.objects.filter(sku_code="UNKNOWNSKU99").exists()
        assert report.rows_unmatched.get(UnmatchedReason.NO_MATCH, 0) == 1


@pytest.mark.django_db(transaction=True)
class TestPOProductEnrichment:
    def setup_method(self) -> None:
        make_product("KCFU64PZHDGR5")
        make_product("KCUF6A4PZHDBL5")

    def test_product_brand_updated(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.brand == "UKN"

    def test_product_copper_weight(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.copper_weight_kg_per_unit == Decimal("17.5")

    def test_product_is_copper_indexed(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.is_copper_indexed is True

    def test_product_gtin(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.gtin == "4897108881749"

    def test_product_hs_code(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.hs_code == "854449 2000"

    def test_product_pallet_qty(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.pallet_qty == 9

    def test_product_description_en(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.description_marketing.get("en") == "CAT6 Cable F/UTP grey 500m"

    def test_product_description_fr(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert p.description_marketing.get("fr") == "CÂBLE CAT6 F/UTP gris 500m"

    def test_product_is_active_true_when_active_france(self) -> None:
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        p.is_active = False
        p.save(update_fields=["is_active"])
        POFournisseursLoader().run(default_config())
        p.refresh_from_db()
        assert p.is_active is True

    def test_update_product_writes_is_active_false(self) -> None:
        """Regression: ``is_active`` must persist ``False``, not only truthy values."""
        p = make_product("KISACT1", is_active=True)
        POFournisseursLoader()._update_product(
            p,
            NormalizedRow(data={"is_active": False}, raw={}),
        )
        p.refresh_from_db()
        assert p.is_active is False


@pytest.mark.django_db(transaction=True)
class TestPOSupplierUpsert:
    def setup_method(self) -> None:
        make_product("KCFU64PZHDGR5")
        make_product("KCUF6A4PZHDBL5")

    def test_two_suppliers_created_for_same_sku(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        assert ProductSupplier.objects.filter(product=p).count() == 2

    def test_supplier_factory_code_china(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        sup = ProductSupplier.objects.get(product=p, factory_code="21")
        assert sup.supplier_name == "HT"
        assert sup.po_base_price == Decimal("448.92")
        assert sup.po_currency == Currency.USD
        assert sup.incoterm == Incoterm.FOB
        assert sup.incoterm_location == "China"

    def test_supplier_factory_code_turkey(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        sup = ProductSupplier.objects.get(product=p, factory_code="E02")
        assert sup.supplier_name == "KK"
        assert sup.incoterm_location == "Turkey"

    def test_supplier_copper_base_price_set(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        for sup in ProductSupplier.objects.filter(product=p):
            assert sup.copper_base_price == Decimal("97000")

    def test_supplier_is_active_false_by_default(self) -> None:
        POFournisseursLoader().run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        for sup in ProductSupplier.objects.filter(product=p):
            assert sup.is_active is False  # migration never activates

    def test_supplier_idempotent_on_re_run(self) -> None:
        loader = POFournisseursLoader()
        loader.run(default_config())
        loader.run(default_config())
        p = Product.objects.get(sku_code="KCFU64PZHDGR5")
        # Still only 2 suppliers (get_or_create is idempotent)
        assert ProductSupplier.objects.filter(product=p).count() == 2


@pytest.mark.django_db(transaction=True)
class TestPODryRun:
    def setup_method(self) -> None:
        make_product("KCFU64PZHDGR5")
        make_product("KCUF6A4PZHDBL5")

    def test_dry_run_no_supplier_created(self) -> None:
        POFournisseursLoader().run(default_config(dry_run=True))
        assert ProductSupplier.objects.count() == 0

    def test_dry_run_no_quarantine_records(self) -> None:
        POFournisseursLoader().run(default_config(dry_run=True))
        assert MigrationUnmatched.objects.count() == 0

    def test_dry_run_report_matched(self) -> None:
        report = POFournisseursLoader().run(default_config(dry_run=True))
        assert report.rows_matched == 3  # empty FOB now tolerated (row 5 matches)
        assert report.rows_updated == 0
        assert report.dry_run is True


class TestPONormalizeRow:
    """Unit tests for normalize_row — no DB, no file I/O."""

    def _make_raw(self, **kwargs: object) -> pd.Series:
        defaults = {
            "sku_code": "KCFU64PZHDGR5",
            "internal_code": "KCFU64PZHDGR5-21",
            "brand": "UKN",
            "active_france": "Yes",
            "active_export": "No",
            "universe": "COPPER",
            "range": "DATA CABLES",
            "sub_range": "SOLID CABLE CAT6",
            "description_en": "CAT6 grey 500m",
            "description_fr": "CÂBLE CAT6 gris 500m",
            "gtin": "4897108881749",
            "hs_code": "854449 2000",
            "copper_weight": "17.5",
            "pallet_qty": "9",
            "fob_price_usd": "448.92",
            "symea_margin_rate": "0.09",
            "supplier_code": "HT",
            "origin": "China",
            "payment_term": "T/T 60 days",
            "moq": "30 km",
        }
        defaults.update(kwargs)
        return pd.Series(defaults)

    def test_factory_code_extracted_from_internal_code(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw()
        norm = loader.normalize_row(row)
        assert norm.data["factory_code"] == "21"

    def test_factory_code_turkey(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(internal_code="KCFU64PZHDGR5-E02")
        norm = loader.normalize_row(row)
        assert norm.data["factory_code"] == "E02"

    def test_factory_code_none_when_internal_code_has_no_hyphen(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(internal_code="KCFU64PZHDGR5")
        norm = loader.normalize_row(row)
        assert norm.data["factory_code"] is None

    def test_gtin_excel_error_is_none(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(gtin="#N/A")
        norm = loader.normalize_row(row)
        assert norm.data["gtin"] is None

    def test_active_flag_true_when_france_yes(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(active_france="Yes", active_export="No")
        norm = loader.normalize_row(row)
        assert norm.data["is_active"] is True

    def test_active_flag_true_when_export_yes(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(active_france="No", active_export="Yes")
        norm = loader.normalize_row(row)
        assert norm.data["is_active"] is True

    def test_active_flag_false_when_both_no(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(active_france="No", active_export="No")
        norm = loader.normalize_row(row)
        assert norm.data["is_active"] is False

    def test_fob_price_decimal(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(fob_price_usd="448.92")
        norm = loader.normalize_row(row)
        assert norm.data["fob_price_usd"] == Decimal("448.92")

    def test_copper_weight_decimal(self) -> None:
        loader = POFournisseursLoader()
        row = self._make_raw(copper_weight="17.5")
        norm = loader.normalize_row(row)
        assert norm.data["copper_weight"] == Decimal("17.5")


class TestPOStorageFactoryKey:
    """Regression: missing Internal Code suffix must not collapse suppliers on ``factory_code=""``."""

    def test_uses_real_suffix_when_present(self) -> None:
        assert (
            POFournisseursLoader._storage_factory_key({"factory_code": "21", "supplier_code": "HT"})
            == "21"
        )

    def test_synthetic_prefix_when_suffix_missing(self) -> None:
        assert (
            POFournisseursLoader._storage_factory_key({"factory_code": None, "supplier_code": "HT"})
            == "?HT"
        )

    def test_raises_when_suffix_and_supplier_missing(self) -> None:
        with pytest.raises(InvalidRowError):
            POFournisseursLoader._storage_factory_key({"factory_code": None, "supplier_code": None})


@pytest.mark.django_db(transaction=True)
class TestPOMissingFactorySuffixSuppliers:
    """Same product, no Internal Code suffix, different Supplier → two ProductSupplier rows."""

    def test_two_distinct_rows_not_merged(self) -> None:
        p = make_product("KMERGE1")
        loader = POFournisseursLoader()
        loader._copper_base_price = Decimal("97000")
        loader._factory_to_name = {}
        base = {
            "sku_code": "KMERGE1",
            "factory_code": None,
            "fob_price_usd": Decimal("100"),
            "copper_weight": None,
            "origin": "China",
        }
        loader.apply_update(p, NormalizedRow(data={**base, "supplier_code": "HT"}, raw={}))
        loader.apply_update(
            p,
            NormalizedRow(
                data={
                    **base,
                    "supplier_code": "ZD",
                    "fob_price_usd": Decimal("200"),
                    "origin": "Turkey",
                },
                raw={},
            ),
        )
        assert ProductSupplier.objects.filter(product=p).count() == 2
        assert ProductSupplier.objects.get(product=p, factory_code="?HT").po_base_price == Decimal(
            "100"
        )
        assert ProductSupplier.objects.get(product=p, factory_code="?ZD").po_base_price == Decimal(
            "200"
        )
